# Generated by Django 5.0.4 on 2024-04-08 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost_Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpcreate_title', models.CharField(max_length=200)),
                ('fpcreate_content', models.TextField()),
                ('fpcreate_image', models.ImageField(blank=True, null=True, upload_to='static/forumpost/forum_images/')),
                ('fpcreate_created_at', models.DateTimeField(auto_now_add=True)),
                ('fpcreate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
