# Generated by Django 5.0.4 on 2024-04-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackreply',
            old_name='fb_admin',
            new_name='fbr_admin',
        ),
        migrations.RenameField(
            model_name='feedbackreply',
            old_name='timestamp',
            new_name='fbr_imestamp',
        ),
        migrations.RenameField(
            model_name='feedbackreply',
            old_name='reply_content',
            new_name='fbr_reply_content',
        ),
    ]
