# Generated by Django 5.0.4 on 2024-04-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_fb_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fb_uname',
            field=models.CharField(max_length=20),
        ),
    ]
