# Generated by Django 5.0.4 on 2024-04-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_author', models.CharField(max_length=50)),
                ('art_title', models.CharField(max_length=100)),
                ('art_content', models.TextField()),
                ('art_image', models.ImageField(default='article_images/default.jpg', upload_to='static/article_images')),
                ('art_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
