# Generated by Django 5.0.4 on 2024-04-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desagent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
